"""add embedding column to chunks

Revision ID: 5fe902b7ebb8
Revises: dbeaecb04f45
Create Date: 2026-08-20 20:09:02.024561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5fe902b7ebb8'
down_revision: Union[str, Sequence[str], None] = 'dbeaecb04f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.add_column('chunks', sa.Column(
        'embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    op.create_table('playing_with_neon',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('value', sa.REAL(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('playing_with_neon_pkey'))
                    )
    # ### end Alembic commands ###
