"""sync current models

Revision ID: dbeaecb04f45
Revises: 
Create Date: 2026-08-20 19:32:03.893159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'dbeaecb04f45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('document_id', sa.UUID(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('chunk_index', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['document_id'], ['documents.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('Chunks')
    op.create_unique_constraint(None, 'documents', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_table('Chunks',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('document_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('content', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('chunk_index', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['document_id'], ['documents.id'], name=op.f('Chunks_document_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('Chunks_pkey'))
                    )
    op.drop_table('chunks')
    # ### end Alembic commands ###
